version: '3.3'
services:
  local_stack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - '4566:4566'
      - '4510-4559:4510-4559'
    networks:
      - app_network
  graphql_app_database:
    image: mariadb
    container_name: graphql_app_database
    environment:
      MARIADB_ROOT_PASSWORD: 123
    volumes:
      - './scripts/database.sql:/docker-entrypoint-initdb.d/1.sql'
    ports:
      - '3306:3306'
    networks:
      - app_network
  graphql_app_product_service:
    build:
      context: ./product-service
      dockerfile: Dockerfile.dev
    container_name: graphql_app_product_service
    env_file: ./product-service/.env
    volumes:
      - ./product-service:/home/app
    ports:
      - '4001:4001'
    networks:
      - app_network
    depends_on:
      - graphql_app_database
  graphql_app_user_service:
    build:
      context: ./user-service
      dockerfile: Dockerfile.dev
    container_name: graphql_app_user_service
    env_file: ./user-service/.env
    volumes:
      - ./user-service:/home/app
    ports:
      - '4002:4002'
    networks:
      - app_network
    depends_on:
      - graphql_app_database
  graphql_app_review_service:
    build:
      context: ./review-service
      dockerfile: Dockerfile.dev
    container_name: graphql_app_review_service
    env_file: ./review-service/.env
    volumes:
      - ./review-service:/home/app
    ports:
      - '4003:4003'
    networks:
      - app_network
    depends_on:
      - graphql_app_database
  graphql_app_gateway_service:
    build:
      context: ./graphql-gateway
      dockerfile: Dockerfile.dev
    container_name: graphql_app_gateway_service
    volumes:
      - ./graphql-gateway:/home/app
    ports:
      - '4000:4000'
    networks:
      - app_network
    depends_on:
      - graphql_app_product_service
      - graphql_app_user_service
      - graphql_app_review_service
networks:
  app_network:
    driver: bridge
